spring.application.name=studentAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/student_api_db
spring.datasource.username=minthanttun
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
